#!/usr/bin/env bash
# vi:syntax=sh
# vi:filetype=sh

# Current script decrypts and opens a gpg-encrypted document that is stored in
# the password-store of the *pass* Unix password manager. Under the hood uses
# xdg-mime to grab the file type and open it with the default application for
# its filetype.
#
# Currently runs on Linux platforms supporing the freedesktop xdg specification
# only

die()
{
	local _ret=$2
	test -n "$_ret" || _ret=1
	test "$_PRINT_HELP" = yes && print_help >&2
	echo "$1" >&2
	exit ${_ret}
}

begins_with_short_option()
{
	local first_option all_short_options
	all_short_options='gh'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

_positionals=()
_arg_gpg_id="$HOME/.password-store/.gpg-id"

print_help ()
{
	printf '%s\n' "Open a gpg-encrypted, optionally pass-stored, file"
	printf 'Usage: %s [-g|--gpg_id <arg>] [-h|--help] <input-file>\n' "$0"
	printf '\t%s\n' "<input-file>: gpg-encrypted file to open. You can either use the full path to the file or just the name of the pass-stored item"
	printf '\t%s\n' "-g, --gpg_id: gpg-id to use. (default: '$HOME/.password-store/.gpg-id')"
	printf '\t%s\n' "-h, --help: Prints help"
}

parse_commandline ()
{
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-g|--gpg_id)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_gpg_id="$2"
				shift
				;;
			--gpg_id=*)
				_arg_gpg_id="${_key##--gpg_id=}"
				;;
			-g*)
				_arg_gpg_id="${_key##-g}"
				;;
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_positionals+=("$1")
				;;
		esac
		shift
	done
}


handle_passed_args_count ()
{
	_required_args_string="'input-file'"
	test ${#_positionals[@]} -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 1 (namely: $_required_args_string), but got only ${#_positionals[@]}." 1
	test ${#_positionals[@]} -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1 (namely: $_required_args_string), but got ${#_positionals[@]} (the last one was: '${_positionals[*]: -1}')." 1
}

assign_positional_args ()
{
	_positional_names=('_arg_input_file' )

	for (( ii = 0; ii < ${#_positionals[@]}; ii++))
	do
		eval "${_positional_names[ii]}=\${_positionals[ii]}" || die "Error during argument parsing, possibly an Argbash bug." 1
	done
}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args

set -e

function print_fatal_msg() {

printf "%s\nExiting...\n" "$1"
exit 1

}

root="$HOME/.password-store/"

gpg_prog="$(which gpg)"
recipient=$(cat "$root/.gpg-id")

open_prog=
del_prog=
del_prog_flags=
if [ $(uname) == "Linux" ]; then
    del_prog=$(which shred)
    del_prog_flags="--remove"
elif [ $(uname) == "Darwin" ]; then
    del_prog=$(which srm)
else
    print_fatal_msg "Unknown platform \($(uname)\)"
fi

# find the correct path to the file
fpath_potential_full="$root/$_arg_input_file.gpg"
if [ -f "$_arg_input_file" ]; then
  fpath="$_arg_input_file"
elif [ -f "$fpath_potential_full" ]; then
  fpath="$fpath_potential_full"
else
  echo "fpath_potential_full:  ${fpath_potential_full}"
    print_fatal_msg "Neither \"$_arg_input_file\" or \"$fpath_potential_full\" exist."
fi

# Decrypt
fname=$(basename $_arg_input_file .gpg)
echo "fname:  ${fname}"
ext="${fname##*.}"
echo "ext:  ${ext}"
dst_file="/tmp/pass-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1).$ext"
${gpg_prog} --recipient "$recipient" --decrypt  --output "$dst_file" "$fpath"

xdg-open "$dst_file" &
wait

# Make sure I delete the destination file
printf "Removing output file... [$dst_file]"
${del_prog} ${del_prog_flags} "$dst_file"
echo "Done!"
exit 0
